[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
    "pants.backend.python",
    #"pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.experimental.python",
]
pants_ignore = [
    "!src/_black_version.py"
]

[source]
root_patterns = [
    '/',
    '/src',
]

[subprocess-environment]
env_vars.add = ["_RUNNING_IN_PANTS=1", "BLACK_USE_MYPYC"]

[anonymous-telemetry]
enabled = true
repo_id = "C6339CF0-26A0-43B3-8DF0-2E8E2A3DE28C"

[python]
interpreter_constraints = [">=3.6.2,<3.11"]
enable_resolves = true
resolves = { python-default = "lockfiles/python-default.lock" }
default_resolve = "python-default"
lockfile_generator = "pex"

[pytest]
lockfile = "lockfiles/pytest.lock"

[mypy]
lockfile = "lockfiles/mypy.lock"
interpreter_constraints = [">=3.6.2"]
extra_type_stubs = [
    "types-typed-ast >= 1.4.2",
    "types-dataclasses >= 0.1.3",
    "typing-extensions > 3.10.0.1",
]
