pex_binary(
    name="driver",
    entry_point="driver.py",
)

pex_binary(
    name="literals",
    entry_point="literals.py",
)

python_sources()

pex_binary(
    name="tokenize",
    entry_point="tokenize.py",
)
