pex_binary(
    name="check_pre_commit_rev_in_example",
    entry_point="check_pre_commit_rev_in_example.py",
)

pex_binary(
    name="check_version_in_basics_example",
    entry_point="check_version_in_basics_example.py",
)

pex_binary(
    name="diff_shades_gha_helper",
    entry_point="diff_shades_gha_helper.py",
)

python_sources()
