python_requirement(
    name="extra-d",
    requirements=["aiohttp>=3.7.4"],
)

python_requirement(
    name="extra-jupyter",
    requirements=["ipython>=7.8.0", "tokenize-rt>=3.2.0"],
)

python_sources()
